/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 03 18:51:00 GMT 2020
 */

package fb;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class FizzBuzz_ESTest extends FizzBuzz_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test0() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo(5);
		assertEquals("5", string0);
	}

	@Test(timeout = 4000)
	public void test1() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo(499);
		assertEquals("499", string0);
	}

	@Test(timeout = 4000)
	public void test2() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo(500);
		assertEquals("bluesoft", string0);
	}

	@Test(timeout = 4000)
	public void test3() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo((-105));
		assertEquals("fizzbuzz", string0);
	}

	@Test(timeout = 4000)
	public void test4() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo((-4473));
		assertEquals("buzz", string0);
	}

	@Test(timeout = 4000)
	public void test5() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo(4433);
		assertEquals("bluesoft", string0);
	}

	@Test(timeout = 4000)
	public void test6() throws Throwable {
		FizzBuzz fizzBuzz0 = new FizzBuzz();
		String string0 = fizzBuzz0.jogo((-3860));
		assertEquals("-3860", string0);
	}
}
